import json
import os

from openai import OpenAI

from config import get_provider

OLLAMA_BASE_URL = "http://localhost:11434/v1"
OLLAMA_MODEL = "qwen2.5"


# =============================================
# Mock provider — deterministic canned answers
# =============================================
# Lets the whole pipeline run offline (frontend dev, demos without
# credits). Responses are keyed off distinctive substrings of each
# agent's system prompt.

_MOCK_FOUNDER_SCORE = {
    "overall_score": 72.0,
    "execution_velocity": 75.0,
    "domain_expertise": 70.0,
    "resilience_history": 65.0,
    "confidence": 0.6,
    "data_completeness": 0.5,
    "trend": "rising",
    "trend_delta": 1.5,
    "is_cold_start": False,
}

_MOCK_RESEARCH = {
    "company_research": {
        "news_summary": "[mock] No live research — provider is set to 'mock'.",
        "hackathon_wins": "",
        "news_links": [],
        "producthunt_signals": "",
    },
    "founders_research": [],
}

_MOCK_AXIS = {"score": 65, "trend": "stable", "confidence": 0.5, "signals": ["[mock] canned answer — no LLM was called"]}

_MOCK_SCREENER = {
    "founder": dict(_MOCK_AXIS),
    "market": dict(_MOCK_AXIS),
    "idea": dict(_MOCK_AXIS),
    "recommendation": "diligence",
}

_MOCK_MEMO = {
    "company_snapshot": "[mock] Memo generated by the mock provider — no LLM was called.",
    "investment_hypotheses": ["[mock] Enable a real provider (openai/ollama) in backend/config.py for real output."],
    "swot": {
        "strengths": [{"statement": "[mock] placeholder", "factors": [], "conflicts": []}],
        "weaknesses": [{"statement": "[mock] placeholder", "factors": [], "conflicts": []}],
        "opportunities": [{"statement": "[mock] placeholder", "factors": [], "conflicts": []}],
        "threats": [{"statement": "[mock] placeholder", "factors": [], "conflicts": []}],
    },
    "recommendation": {"action": "diligence", "confidence": "LOW", "reasoning": "[mock] provider"},
    "open_questions": ["[mock] Switch LLM_PROVIDER to get real analysis."],
}

# (needle in system prompt, canned response) — first match wins
_MOCK_ROUTES = [
    ("Founder Score", _MOCK_FOUNDER_SCORE),
    ("REAL RAW", _MOCK_RESEARCH),
    ("screening AI", _MOCK_SCREENER),
    ("investment memo", _MOCK_MEMO),
]


def _mock_answer(messages: list, response_format=None) -> str:
    system = " ".join(m.get("content", "") for m in messages if m.get("role") == "system")
    for needle, canned in _MOCK_ROUTES:
        if needle in system:
            return json.dumps(canned)
    if response_format and response_format.get("type") == "json_object":
        return "{}"
    return "[mock] canned answer — no LLM was called."


class _MockMessage:
    def __init__(self, content):
        self.content = content


class _MockChoice:
    def __init__(self, content):
        self.message = _MockMessage(content)


class _MockCompletion:
    def __init__(self, content):
        self.choices = [_MockChoice(content)]


class _MockCompletions:
    def create(self, model=None, messages=None, response_format=None, **kwargs):
        return _MockCompletion(_mock_answer(messages or [], response_format))


class _MockChat:
    def __init__(self):
        self.completions = _MockCompletions()


class MockOpenAIClient:
    """Drop-in stand-in for OpenAI().chat.completions.create."""

    def __init__(self):
        self.chat = _MockChat()


def _default_instance(model_cls):
    """Build a pydantic instance filled with neutral placeholder values."""
    from typing import get_args, get_origin

    values = {}
    for name, field in model_cls.model_fields.items():
        ann = field.annotation
        origin = get_origin(ann)
        if origin is list:
            (inner,) = get_args(ann) or (str,)
            if hasattr(inner, "model_fields"):
                values[name] = [_default_instance(inner)]
            else:
                values[name] = []
        elif hasattr(ann, "model_fields"):
            values[name] = _default_instance(ann)
        elif ann is str:
            values[name] = f"[mock] {name}"
        elif ann is int:
            values[name] = 50
        elif ann is float:
            values[name] = 0.5
        elif ann is bool:
            values[name] = False
        else:
            values[name] = None
    return model_cls(**values)


class _MockStructuredRunnable:
    def __init__(self, schema):
        self.schema = schema

    def invoke(self, _prompt):
        return _default_instance(self.schema)


class MockLangchainLLM:
    """Stand-in for ChatOpenAI supporting with_structured_output()."""

    def with_structured_output(self, schema):
        return _MockStructuredRunnable(schema)

    def invoke(self, _prompt):
        return _MockMessage("[mock] canned answer — no LLM was called.")


# =============================================
# Public factory functions
# =============================================

def get_llm_client():
    """OpenAI-compatible client for the configured provider (openai/ollama/mock)."""
    provider = get_provider()
    if provider == "mock":
        return MockOpenAIClient()
    if provider == "ollama":
        return OpenAI(base_url=OLLAMA_BASE_URL, api_key="ollama")  # key required but unused
    return OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def get_langchain_llm(temperature=0):
    """LangChain chat model for the configured provider (openai/ollama/mock)."""
    provider = get_provider()
    if provider == "mock":
        return MockLangchainLLM()
    from langchain_openai import ChatOpenAI

    if provider == "ollama":
        return ChatOpenAI(base_url=OLLAMA_BASE_URL, api_key="ollama", model=OLLAMA_MODEL, temperature=temperature)
    return ChatOpenAI(model="gpt-4o", temperature=temperature, api_key=os.getenv("OPENAI_API_KEY"))


def get_model_name(default_model="gpt-4o") -> str:
    """Model name matching the configured provider."""
    provider = get_provider()
    if provider == "ollama":
        return OLLAMA_MODEL
    if provider == "mock":
        return "mock"
    return default_model
