import React, { useState, useEffect } from "react";
import { FileText, Loader2, Target, ShieldCheck, FileSearch } from "lucide-react";

export default function MemoApp() {
  const [applications, setApplications] = useState<any[]>([]);
  const [selectedApp, setSelectedApp] = useState<string | null>(null);
  const [memo, setMemo] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [fetchingApps, setFetchingApps] = useState(true);

  useEffect(() => {
    fetch("http://localhost:8000/api/applications")
      .then(res => res.json())
      .then(data => {
        setApplications(data);
        setFetchingApps(false);
      })
      .catch(err => {
        console.error(err);
        setFetchingApps(false);
      });
  }, []);

  const handleGenerateMemo = (appId: string) => {
    setLoading(true);
    fetch(`http://localhost:8000/api/memo/generate/${appId}`, { method: "POST" })
      .then(res => res.json())
      .then(data => {
        setMemo(data.memo?.content_json || {});
        setSelectedApp(appId);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  };

  const loadExistingMemo = (appId: string) => {
    setLoading(true);
    fetch(`http://localhost:8000/api/memo/${appId}`)
      .then(res => res.json())
      .then(data => {
        if (data.content_json) {
          setMemo(data.content_json);
          setSelectedApp(appId);
        } else {
          // No memo exists, generate one
          handleGenerateMemo(appId);
        }
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  };

  if (fetchingApps) {
    return (
      <div className="flex h-full w-full items-center justify-center bg-[#0a0a0c]">
        <Loader2 className="animate-spin text-gold-400" size={32} />
      </div>
    );
  }

  return (
    <div className="h-full flex bg-[#0a0a0c] text-white">
      {/* Sidebar - App Selection */}
      <div className="w-64 border-r border-white/5 bg-[#121214] p-4 flex flex-col gap-2 overflow-y-auto">
        <h3 className="text-sm font-bold text-white/50 uppercase tracking-wider mb-2">Deal Flow</h3>
        {applications.length === 0 ? (
          <p className="text-white/40 text-sm">No applications available.</p>
        ) : (
          applications.map(app => (
            <button
              key={app.id}
              onClick={() => loadExistingMemo(app.id)}
              className={`text-left p-3 rounded-lg transition-colors border ${
                selectedApp === app.id ? "bg-white/10 border-white/10" : "bg-transparent border-transparent hover:bg-white/5"
              }`}
            >
              <div className="font-bold truncate">{app.startups?.name || "Unknown"}</div>
              <div className="text-xs text-white/50 capitalize mt-1">{app.status}</div>
            </button>
          ))
        )}
      </div>

      {/* Main Content - Memo Display */}
      <div className="flex-1 p-8 overflow-y-auto">
        {!selectedApp ? (
          <div className="h-full flex flex-col items-center justify-center text-center text-white/40">
            <FileSearch size={48} className="mb-4 opacity-50" />
            <h3 className="text-lg font-bold text-white mb-2">Investment Memos</h3>
            <p className="max-w-md">Select an application from the sidebar to view or generate its evidence-backed investment memo.</p>
          </div>
        ) : loading ? (
          <div className="h-full flex flex-col items-center justify-center text-center">
            <Loader2 className="animate-spin text-gold-400 mb-4" size={32} />
            <h3 className="font-bold text-white">Generating Memo...</h3>
            <p className="text-white/50 text-sm">Synthesizing extraction, web research, and trust scores.</p>
          </div>
        ) : memo ? (
          <div className="max-w-3xl mx-auto space-y-8 pb-12">
            <div className="border-b border-white/10 pb-6">
              <h1 className="text-3xl font-bold mb-2">Investment Memo</h1>
              <p className="text-white/50">Auto-generated by VC Brain AI Agent</p>
            </div>

            {/* Recommendation Badge */}
            <div className="bg-black/40 p-4 rounded-xl border border-white/10 flex items-center justify-between">
              <div>
                <div className="text-xs text-white/50 uppercase tracking-wider mb-1">Recommendation</div>
                <div className={`text-xl font-bold uppercase ${
                  memo.recommendation === 'deploy' ? 'text-green-400' :
                  memo.recommendation === 'diligence' ? 'text-blue-400' : 'text-yellow-400'
                }`}>
                  {memo.recommendation || "DILIGENCE"}
                </div>
              </div>
              <ShieldCheck className="text-gold-400" size={32} />
            </div>

            {/* Sections */}
            {[
              { id: 'company_snapshot', title: 'Company Snapshot' },
              { id: 'investment_hypotheses', title: 'Investment Hypotheses' },
              { id: 'swot', title: 'SWOT Analysis' },
              { id: 'problem_product', title: 'Problem & Product' },
              { id: 'team_history', title: 'Team & History' },
              { id: 'tech_defensibility', title: 'Tech & Defensibility' },
              { id: 'market_sizing', title: 'Market Sizing' },
              { id: 'traction_kpis', title: 'Traction & KPIs' },
              { id: 'financials_round', title: 'Financials & Round' },
              { id: 'cap_table', title: 'Cap Table' }
            ].map(section => (
              <section key={section.id} className="space-y-3">
                <h2 className="text-lg font-bold text-gold-400">{section.title}</h2>
                <div className="text-white/80 leading-relaxed text-sm whitespace-pre-wrap">
                  {typeof memo[section.id] === 'string' 
                    ? memo[section.id] 
                    : Array.isArray(memo[section.id])
                      ? <ul className="list-disc pl-5 space-y-2">{memo[section.id].map((i: string, idx: number) => <li key={idx}>{i}</li>)}</ul>
                      : memo[section.id] || <span className="italic text-white/40">Not disclosed.</span>}
                </div>
              </section>
            ))}

            <div className="mt-12 pt-6 border-t border-white/10 text-center text-xs text-white/30">
              Generated via VC Brain AI Pipeline. Citations and trust scores are based on real-time web research.
            </div>
          </div>
        ) : (
          <div className="h-full flex items-center justify-center">
            <p className="text-white/40">Failed to load memo.</p>
          </div>
        )}
      </div>
    </div>
  );
}
